### ISSUE TITLE
When I setup the Quick Keys, press save and close the Preferences box, this message is displayed.

### ISSUE THREAD

**Issue by Maheshchiramure** [luoliyan/incremental-reading-for-anki#5]
Traceback (most recent call last):
File "C:\Users\Mahesh\Documents\Anki\addons\ir\main.py", line 105, in showSettingsDialog mw.settingsManager.showSettingsDialog() File "C:\Users\Mahesh\Documents\Anki\addons\ir\settings.py", line 166, in showSettingsDialog mw.viewManager.resetZoom(mw.state) AttributeError: ViewManager instance has no attribute 'resetZoom'

I have also mentioned it here:

https://anki.tenderapp.com/discussions/add-ons/9028-incremental-reading-v360-error

**Comment by luoliyan** [comment]
I've posted an updated version. I don't know if it will address the problem, but it may.

Please delete the "ir" folder from your add-ons folder, then reinstall the add-on ([click here](https://ankiweb.net/shared/info/1081195335)).

If you still have the same problem, I'll have closer look.

**Comment by luoliyan** [comment]
This should be solved if you remove `Incremental_Reading_Extension.py` and `View_Size_Adjust.py` from your add-ons folder.
