### ISSUE TITLE
ViewManager instance has no attribute 'acsCount'

### ISSUE THREAD

**Issue by chromial** [luoliyan/incremental-reading-for-anki#7]
Installed incremental reading addon. After restart received error below:

![anki](https://cloud.githubusercontent.com/assets/1315665/22756822/6cd32ac6-ee16-11e6-9f24-ce71647c6cb2.PNG)

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\webview.py", line 21, in link
  File "aqt\overview.py", line 37, in _linkHandler
  File "anki\hooks.py", line 59, in repl
  File "aqt\main.py", line 388, in moveToState
  File "anki\hooks.py", line 61, in repl
  File "C:\Users\ljtys\OneDrive\Documents\Anki\addons\View_Size_Adjust.py", line 770, in vsa_reviewState
    if(self.viewManager.acsCount - self.viewManager.rsCount == 1):
AttributeError: ViewManager instance has no attribute 'acsCount'

**Comment by luoliyan** [comment]
This is occurring because you have an older version of IR still installed. If you update to the latest version ([link](https://github.com/luoliyan/incremental-reading-for-anki/archive/dev.zip)), the add-on will disable the old files for you.

Otherwise, you can just delete `Incremental_Reading_Extension.py` and `View_Size_Adjust.py` from your add-ons folder. Everything should work then.
